import type { Plan } from "@/types/plan.types";

export const PLANS: Plan[] = [
  {
    id: "plan_starter",
    name: "Starter",
    slug: "starter",
    price_monthly: 0,
    price_yearly: 0,
    max_websites: 1,
    max_pages_per_site: 5,
    max_storage_mb: 100,
    max_ai_credits: 10,
    custom_domain: false,
    features: [
      "1 website",
      "5 pages per site",
      "100 MB storage",
      "10 AI credits",
      "Free subdomain",
      "Basic analytics",
    ],
  },
  {
    id: "plan_growth",
    name: "Growth",
    slug: "growth",
    price_monthly: 19,
    price_yearly: 190,
    max_websites: 5,
    max_pages_per_site: 20,
    max_storage_mb: 1024,
    max_ai_credits: 100,
    custom_domain: true,
    features: [
      "5 websites",
      "20 pages per site",
      "1 GB storage",
      "100 AI credits",
      "Custom domain",
      "Advanced analytics",
      "Team collaboration (3 members)",
      "Priority support",
    ],
  },
  {
    id: "plan_pro",
    name: "Pro",
    slug: "pro",
    price_monthly: 49,
    price_yearly: 490,
    max_websites: 20,
    max_pages_per_site: 50,
    max_storage_mb: 5120,
    max_ai_credits: 500,
    custom_domain: true,
    features: [
      "20 websites",
      "50 pages per site",
      "5 GB storage",
      "500 AI credits",
      "Custom domain",
      "Full analytics suite",
      "Unlimited team members",
      "Custom HTML blocks",
      "Version history",
      "White-label option",
    ],
  },
];
